import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';

const script=readFileSync(new URL('../apps/android/app/src/main/assets/terminal/mobile.js',import.meta.url),'utf8');
const sent=[];
const selected=[];
const terminal={input:t=>sent.push(t),paste:t=>sent.push(t),hasSelection:()=>false,clearSelection(){},getSelection:()=>'',rows:24,
  selectionManager:{},getScrollbackLength:()=>100,getViewportY:()=>20,selectLines:(a,b)=>selected.push([a,b])};
const first={id:'tab-1',gatewaySessionId:'one',status:'live',controller:{terminal,fit(){}}};
const sessions={tabs:[first],activeId:'tab-1',closeTab(){this.tabs=[];this.activeId=null;},async openSession(){this.tabs=[{...first,id:'tab-2',gatewaySessionId:'two'}];this.activeId='tab-2';}};
const gateway={phase:'connected'};
const panel={available:true,renderRoot:{querySelector:()=>true},terminalSessions:sessions};
const sandbox={window:{},document:{querySelector:s=>s==='openclaw-terminal-panel'?panel:{runtime:{context:{gateway:{snapshot:gateway}}}}}};
vm.runInNewContext(script,sandbox);
const mobile=sandbox.window.clawTerminal;
assert.equal(mobile.snapshot().phase,'live');
assert.equal(terminal.selectionManager.getViewportY(),80);
mobile.select(0,false); mobile.select(0.5,true);
assert.deepEqual(selected,[[0,0],[0,12]]);
assert.equal(mobile.input('hello'),true);
gateway.phase='disconnected';
assert.equal(mobile.input('MUST_NOT_REPLAY'),false);
gateway.phase='connected';
gateway.lastErrorCode='AUTH_DEVICE_TOKEN_MISMATCH';
gateway.phase='offline';
assert.equal(mobile.snapshot().phase,'authorizationRequired');
assert.equal(mobile.input('UNAUTHORIZED'),false);
gateway.phase='connected';gateway.lastErrorCode=null;
assert.equal(mobile.snapshot().phase,'live');
assert.deepEqual(sent,['hello']);
sessions.tabs[0]={...first,gatewaySessionId:'replacement'};
assert.equal(mobile.snapshot().phase,'replaced');
assert.equal(mobile.input('MUST_NOT_ENTER_NEW_SHELL'),false);
mobile.acknowledge();
assert.equal(mobile.snapshot().phase,'live');
sessions.tabs[0].status='exited';
assert.equal(mobile.snapshot().phase,'exited');
assert.equal(mobile.paste('MUST_NOT_REPLAY'),false);
await mobile.newSession();
assert.equal(sessions.tabs.length,1);
assert.equal(mobile.snapshot().phase,'live');
assert.deepEqual(sent,['hello']);
panel.available=false;
assert.equal(mobile.snapshot().phase,'unavailable');
assert.equal(mobile.input('DISABLED'),false);
panel.available=true;
const reloaded={window:{__clawPreviousSession:'old-session'},document:sandbox.document};
vm.runInNewContext(script,reloaded);
assert.equal(reloaded.window.clawTerminal.snapshot().phase,'replaced');
assert.equal(reloaded.window.clawTerminal.input('RELOADED_INPUT'),false);
const restored={window:{__clawPreviousSession:'two'},document:sandbox.document};
vm.runInNewContext(script,restored);
assert.equal(restored.window.clawTerminal.snapshot().phase,'live');
gateway.lastErrorCode='AUTH_TOKEN_MISSING';
assert.equal(restored.window.clawTerminal.snapshot().phase,'live');
gateway.lastErrorCode=null;
const exited={window:{__clawPreviousSession:'two'},document:sandbox.document};
sessions.tabs[0].status='exited';
vm.runInNewContext(script,exited);
assert.equal(exited.window.clawTerminal.snapshot().phase,'exited');
assert.equal(exited.window.clawTerminal.input('DEAD_SHELL_INPUT'),false);
assert.deepEqual(sent,['hello']);
console.log('Terminal mobile adapter: lifecycle, input gates, replacement acknowledgement, single-session recovery passed.');
