#!/usr/bin/env node

import {createHash} from 'node:crypto';
import {readdir, readFile, writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const appRoot = path.join(root, 'apps/android/app');
const sourceRoots = [
  path.join(appRoot, 'src/main/java'),
  path.join(appRoot, 'src/play/java'),
  path.join(appRoot, 'src/thirdParty/java'),
];
const mainValues = path.join(appRoot, 'src/main/res/values');
const chineseValues = path.join(appRoot, 'src/main/res/values-zh-rCN');
const thirdPartyValues = path.join(appRoot, 'src/thirdParty/res/values');
const thirdPartyChineseValues = path.join(appRoot, 'src/thirdParty/res/values-zh-rCN');
const generatedEnglish = path.join(mainValues, 'i18n_generated.xml');
const generatedChinese = path.join(chineseValues, 'i18n_generated.xml');
const kotlinMapPath = path.join(
  appRoot,
  'src/main/java/ai/openclaw/app/i18n/NativeStringResources.kt',
);
const translationsPath = path.join(appRoot, 'src/main/i18n/zh-CN.json');
const generatedHeader = '// Generated by scripts/android-i18n.mjs. Do not edit.';
const supportedResourceDirectories = new Set(['values', 'values-night', 'values-zh-rCN']);

async function filesBelow(directory, predicate = () => true) {
  const entries = await readdir(directory, {withFileTypes: true}).catch(() => []);
  const files = [];
  for (const entry of entries) {
    const absolute = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await filesBelow(absolute, predicate));
    else if (entry.isFile() && predicate(absolute)) files.push(absolute);
  }
  return files;
}

function decodeKotlin(value) {
  return value
    .replaceAll('\\n', '\n')
    .replaceAll('\\"', '"')
    .replaceAll('\\$', '$')
    .replaceAll('\\\\', '\\');
}

function escapeKotlin(value) {
  return value
    .replaceAll('\\', '\\\\')
    .replaceAll('"', '\\"')
    .replaceAll('$', '\\$')
    .replaceAll('\n', '\\n');
}

function decodeXml(value) {
  const trimmed = value.trim();
  const unquoted = trimmed.startsWith('"') && trimmed.endsWith('"')
    ? trimmed.slice(1, -1)
    : trimmed;
  return unquoted
    .replaceAll('&lt;', '<')
    .replaceAll('&gt;', '>')
    .replaceAll('&quot;', '"')
    .replaceAll('&apos;', "'")
    .replaceAll('&amp;', '&')
    .replaceAll('\\n', '\n')
    .replaceAll("\\'", "'")
    .replaceAll('\\"', '"')
    .replaceAll('\\\\', '\\');
}

function escapeXml(value) {
  return value
    .replaceAll('\\', '\\\\')
    .replaceAll('\n', '\\n')
    .replaceAll("'", "\\'")
    .replaceAll('"', '\\"')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');
}

function parseStrings(xml, file) {
  const entries = [];
  const pattern = /<string\s+name="([A-Za-z0-9_]+)"([^>]*)>([\s\S]*?)<\/string>/gu;
  for (const match of xml.matchAll(pattern)) {
    entries.push({
      attrs: match[2] ?? '',
      file,
      key: match[1],
      rawValue: match[3] ?? '',
      value: decodeXml(match[3] ?? ''),
    });
  }
  return entries;
}

async function readResourceDirectory(directory, excluded = new Set()) {
  const resources = new Map();
  const files = (await filesBelow(directory, file => file.endsWith('.xml'))).sort();
  for (const file of files) {
    if (excluded.has(file)) continue;
    for (const entry of parseStrings(await readFile(file, 'utf8'), file)) {
      if (resources.has(entry.key)) {
        throw new Error(`Duplicate string resource ${entry.key}: ${resources.get(entry.key).file}, ${file}`);
      }
      resources.set(entry.key, entry);
    }
  }
  return resources;
}

function parseKotlinMap(source) {
  const entries = new Map();
  const pattern = /"((?:\\.|[^"\\])*)"\s+to\s+R\.string\.([A-Za-z0-9_]+)/gu;
  for (const match of source.matchAll(pattern)) entries.set(decodeKotlin(match[1]), match[2]);
  return entries;
}

function findFirstArgument(source, opening) {
  let round = 1;
  let square = 0;
  let curly = 0;
  let quote = null;
  let escaped = false;
  for (let index = opening + 1; index < source.length; index += 1) {
    if (quote === 'raw') {
      if (source.startsWith('"""', index)) {
        quote = null;
        index += 2;
      }
      continue;
    }
    const character = source[index];
    if (quote === 'string') {
      if (escaped) escaped = false;
      else if (character === '\\') escaped = true;
      else if (character === '"') quote = null;
      continue;
    }
    if (source.startsWith('"""', index)) {
      quote = 'raw';
      index += 2;
    } else if (character === '"') quote = 'string';
    else if (character === '(') round += 1;
    else if (character === ')') {
      round -= 1;
      if (round === 0) return source.slice(opening + 1, index);
    } else if (character === '[') square += 1;
    else if (character === ']') square -= 1;
    else if (character === '{') curly += 1;
    else if (character === '}') curly -= 1;
    else if (character === ',' && round === 1 && square === 0 && curly === 0) {
      return source.slice(opening + 1, index);
    }
  }
  throw new Error('Unbalanced native string call');
}

export function collectNativeSources(source) {
  const sources = new Set();
  const callPattern = /\bnative(?:StringResource|String|Text)\s*\(/gu;
  for (const call of source.matchAll(callPattern)) {
    const opening = (call.index ?? 0) + call[0].lastIndexOf('(');
    const firstArgument = findFirstArgument(source, opening);
    const literalPattern = /"""([\s\S]*?)"""|"((?:\\.|[^"\\])*)"/gu;
    for (const literal of firstArgument.matchAll(literalPattern)) {
      const value = literal[1] ?? decodeKotlin(literal[2] ?? '');
      if (value.trim()) sources.add(value);
    }
  }
  return sources;
}

function resourceKey(source) {
  return `native_${createHash('sha256').update(source).digest('hex').slice(0, 16)}`;
}

function readKotlinInterpolations(source) {
  const interpolations = [];
  for (let index = 0; index < source.length; index += 1) {
    if (source[index] !== '$') continue;
    const next = source[index + 1];
    if (next !== '{' && !/[A-Za-z_]/u.test(next ?? '')) continue;
    const start = index;
    if (next !== '{') {
      index += 2;
      while (/[A-Za-z0-9_]/u.test(source[index] ?? '')) index += 1;
      interpolations.push({start, end: index, value: source.slice(start, index)});
      index -= 1;
      continue;
    }
    let depth = 1;
    let quote = null;
    let escaped = false;
    for (index += 2; index < source.length; index += 1) {
      const character = source[index];
      if (escaped) escaped = false;
      else if (quote !== null && character === '\\') escaped = true;
      else if (character === quote) quote = null;
      else if (quote === null && (character === '"' || character === "'")) quote = character;
      else if (quote === null && character === '{') depth += 1;
      else if (quote === null && character === '}') {
        depth -= 1;
        if (depth === 0) {
          interpolations.push({start, end: index + 1, value: source.slice(start, index + 1)});
          break;
        }
      }
    }
    if (depth !== 0) throw new Error(`Unbalanced interpolation in ${JSON.stringify(source)}`);
  }
  return interpolations;
}

function renderAndroidValue(source, translation) {
  const sourceTokens = readKotlinInterpolations(source).map(item => item.value);
  const translatedTokens = readKotlinInterpolations(translation);
  const sorted = values => [...values].sort().join('\u0000');
  if (sorted(sourceTokens) !== sorted(translatedTokens.map(item => item.value))) {
    throw new Error(`Translation changed placeholders: ${JSON.stringify(source)} -> ${JSON.stringify(translation)}`);
  }
  const indexes = new Map();
  sourceTokens.forEach((token, index) => indexes.set(token, [...(indexes.get(token) ?? []), index + 1]));
  const occurrences = new Map();
  let cursor = 0;
  let rendered = '';
  for (const token of translatedTokens) {
    rendered += translation.slice(cursor, token.start).replaceAll('%', '%%');
    const occurrence = occurrences.get(token.value) ?? 0;
    occurrences.set(token.value, occurrence + 1);
    rendered += `%${indexes.get(token.value)[occurrence]}$s`;
    cursor = token.end;
  }
  rendered += translation.slice(cursor).replaceAll('%', '%%');
  return escapeXml(rendered);
}

function renderGeneratedXml(entries, chinese) {
  const lines = ['<resources xmlns:tools="http://schemas.android.com/tools">'];
  for (const [source, translation] of entries) {
    const formatted = readKotlinInterpolations(source).length > 0 ? '' : ' formatted="false"';
    const value = chinese ? translation : source;
    lines.push(
      `    <string name="${resourceKey(source)}"${formatted} tools:ignore="Typos,TypographyDashes,TypographyEllipsis">"${renderAndroidValue(source, value)}"</string>`,
    );
  }
  lines.push('</resources>', '');
  return lines.join('\n');
}

function renderKotlin(entries) {
  return [
    generatedHeader,
    'package ai.openclaw.app.i18n',
    '',
    'import ai.openclaw.app.R',
    '',
    'internal val nativeStringResourceIds: Map<String, Int> =',
    '  mapOf(',
    ...entries.map(([source, key]) => `    "${escapeKotlin(source)}" to R.string.${key},`),
    '  )',
    '',
  ].join('\n');
}

function placeholders(value) {
  return [...value.matchAll(/%\d+\$[a-z]/giu)].map(match => match[0]).sort().join('\u0000');
}

async function unsupportedLocaleDirectories() {
  const findings = [];
  for (const resourceRoot of [path.join(appRoot, 'src/main/res'), path.join(appRoot, 'src/thirdParty/res')]) {
    const directories = await readdir(resourceRoot, {withFileTypes: true});
    for (const directory of directories) {
      if (directory.isDirectory() && directory.name.startsWith('values-') && !supportedResourceDirectories.has(directory.name)) {
        findings.push(path.relative(root, path.join(resourceRoot, directory.name)));
      }
    }
  }
  return findings.sort();
}

async function build() {
  const [kotlinSource, translationSource, sourceFiles] = await Promise.all([
    readFile(kotlinMapPath, 'utf8'),
    readFile(translationsPath, 'utf8').catch(() => '{}'),
    Promise.all(sourceRoots.map(sourceRoot => filesBelow(sourceRoot, file => file.endsWith('.kt')))),
  ]);
  const translations = JSON.parse(translationSource);
  const catalogEntries = Object.entries(translations).sort(([left], [right]) => left.localeCompare(right));
  const nativeSources = new Set(catalogEntries.map(([source]) => source));
  for (const file of sourceFiles.flat()) {
    for (const source of collectNativeSources(await readFile(file, 'utf8'))) nativeSources.add(source);
  }

  const existingMap = parseKotlinMap(kotlinSource);
  const baseWithoutGenerated = await readResourceDirectory(mainValues, new Set([generatedEnglish]));
  const baseValueToKey = new Map([...baseWithoutGenerated.values()].map(entry => [entry.value, entry.key]));
  // Generated resources mirror the current source/catalog; removed UI copy is not a compatibility API.
  const mapping = new Map([...existingMap].filter(([source]) => nativeSources.has(source)));
  const missingTranslations = [];
  for (const source of [...nativeSources].sort()) {
    if (mapping.has(source)) continue;
    const manualKey = baseValueToKey.get(source);
    if (manualKey) mapping.set(source, manualKey);
    else if (Object.hasOwn(translations, source)) mapping.set(source, resourceKey(source));
    else missingTranslations.push(source);
  }

  const ownedEntries = catalogEntries.filter(([source]) => {
    const mapped = existingMap.get(source);
    return mapped === undefined || mapped === resourceKey(source);
  });
  const generatedKeys = new Set(ownedEntries.map(([source]) => resourceKey(source)));
  const availableKeys = new Set([...baseWithoutGenerated.keys(), ...generatedKeys]);
  const danglingMappings = [...mapping].filter(([, key]) => !availableKeys.has(key));
  const orderedMapping = [
    ...[...existingMap].filter(([source]) => nativeSources.has(source)),
    ...[...mapping].filter(([source]) => !existingMap.has(source)).sort(([left], [right]) => left.localeCompare(right)),
  ];
  const duplicateSources = orderedMapping.length - new Set(orderedMapping.map(([source]) => source)).size;
  const duplicateKeys = ownedEntries.length - generatedKeys.size;

  return {
    danglingMappings,
    duplicateKeys,
    duplicateSources,
    expectedEnglish: renderGeneratedXml(ownedEntries, false),
    expectedChinese: renderGeneratedXml(ownedEntries, true),
    expectedKotlin: renderKotlin(orderedMapping),
    missingTranslations,
    mapping,
    unsupportedLocales: await unsupportedLocaleDirectories(),
  };
}

async function validateResources(state) {
  const problems = [];
  for (const [label, baseDirectory, localizedDirectory] of [
    ['app', mainValues, chineseValues],
    ['third-party', thirdPartyValues, thirdPartyChineseValues],
  ]) {
    const [base, localized] = await Promise.all([
      readResourceDirectory(baseDirectory),
      readResourceDirectory(localizedDirectory),
    ]);
    for (const [key, entry] of base) {
      if (entry.attrs.includes('translatable="false"')) continue;
      const translated = localized.get(key);
      if (!translated) problems.push(`${label}: zh-CN missing ${key}`);
      else if (placeholders(entry.rawValue) !== placeholders(translated.rawValue)) {
        problems.push(`${label}: zh-CN placeholder mismatch ${key}`);
      }
    }
    for (const key of localized.keys()) {
      if (!base.has(key)) problems.push(`${label}: zh-CN extra ${key}`);
    }
  }
  problems.push(...state.unsupportedLocales.map(directory => `unsupported locale directory: ${directory}`));
  problems.push(...state.danglingMappings.map(([source, key]) => `missing resource ${key} for ${JSON.stringify(source)}`));
  if (state.duplicateSources) problems.push('duplicate Kotlin source mappings');
  if (state.duplicateKeys) problems.push('generated resource hash collision');
  return problems;
}

export async function syncAndroidI18n() {
  const state = await build();
  if (state.missingTranslations.length) {
    throw new Error(`Missing zh-CN translations:\n${state.missingTranslations.map(JSON.stringify).join('\n')}`);
  }
  await Promise.all([
    writeFile(generatedEnglish, state.expectedEnglish),
    writeFile(generatedChinese, state.expectedChinese),
    writeFile(kotlinMapPath, state.expectedKotlin),
  ]);
  await checkAndroidI18n();
}

export async function checkAndroidI18n() {
  const state = await build();
  const problems = await validateResources(state);
  if (state.missingTranslations.length) {
    problems.push(...state.missingTranslations.map(source => `missing zh-CN translation: ${JSON.stringify(source)}`));
  }
  for (const [file, expected] of [
    [generatedEnglish, state.expectedEnglish],
    [generatedChinese, state.expectedChinese],
    [kotlinMapPath, state.expectedKotlin],
  ]) {
    const current = await readFile(file, 'utf8').catch(() => '');
    if (current !== expected) problems.push(`generated file is stale: ${path.relative(root, file)}`);
  }
  if (problems.length) throw new Error(`Android i18n check failed:\n${problems.join('\n')}`);
  process.stdout.write(`PASS Android i18n: default=en, locales=en,zh-CN, mapped=${state.mapping.size}\n`);
}

const command = process.argv[2];
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (command === 'sync') await syncAndroidI18n();
  else if (command === 'check') await checkAndroidI18n();
  else throw new Error('Usage: node scripts/android-i18n.mjs <sync|check>');
}
